return {
  { "Isrothy/neominimap.nvim" },
  { "tpope/vim-sensible" },
  { "tpope/vim-surround" },
  { "tpope/vim-fugitive" },
  { "tpope/vim-abolish" },
  { "tpope/vim-eunuch" },
  { "tpope/vim-commentary" },
  { "nvim-lua/plenary.nvim" },
  { "lewis6991/gitsigns.nvim" },
  { "nvim-tree/nvim-web-devicons" },
  { "nvim-treesitter/nvim-treesitter" },
  { "nvim-lualine/lualine.nvim" },
  { "lukas-reineke/indent-blankline.nvim" },
  { "neovim/nvim-lspconfig" },
  { "mason-org/mason.nvim" },
  { "mason-org/mason-lspconfig.nvim" },
  { "simrat39/rust-tools.nvim" },
  { "windwp/nvim-autopairs" },
  { "RRethy/vim-illuminate" },
  { "numToStr/Comment.nvim" },
  { "danilamihailov/beacon.nvim" },
  { "folke/zen-mode.nvim" },
  { "ThePrimeagen/vim-be-good" },
}
